import { Modal } from '@/components/ui/Modal';
import { Badge, Button } from '@/components/ui/Surface';
import Icon from '@/components/ui/Icon';
import { useBrand } from '@/brand/BrandProvider';
import { formatCurrency, formatDate, formatDateTime } from '@/utils/format';

/**
 * COMPILED PACKET — the single document the blocks add up to.
 *
 * The editor shows the packet as parts you can reorder and exclude, which is
 * right for building it and wrong for checking it: nobody can tell what an
 * issuer will actually receive by reading a list of nine collapsible cards.
 * This renders the same blocks, in order, as one continuous representment on
 * the same letterhead the case documents use.
 *
 * IT COMPILES WHAT IS INCLUDED, NOTHING ELSE. Excluded blocks are absent
 * rather than greyed, because the question this screen answers is "what am I
 * about to send", and a greyed block on a preview is exactly the ambiguity
 * that gets an unredacted exhibit shipped.
 *
 * The exhibit index is generated from the blocks rather than typed, so it
 * cannot drift from what follows it — a numbered list promising five exhibits
 * above four exhibits is the kind of detail an issuer uses to reject a packet.
 */

function Exhibit({ block, index }) {
  return (
    <section className="compiled__exhibit">
      <h3 className="compiled__exhibit-head">
        Exhibit {index} — {block.title}
        {block.redactions?.length > 0 && (
          <Badge tone="success" dot>{block.redactions.length} redacted</Badge>
        )}
      </h3>

      {block.kind === 'screenshot' && block.dataUrl && (
        <img src={block.dataUrl} alt={block.title} className="compiled__image" />
      )}

      {block.kind === 'attachment' && (
        <div className="compiled__attachment">
          <Icon name="file" size={16} className="subtle" />
          <span>
            <span className="small strong" style={{ display: 'block' }}>{block.title}</span>
            <span className="nano subtle">
              {block.mimeType}
              {block.size ? ` · ${Math.max(1, Math.round(block.size / 1024))} KB` : ''}
              {' · supplied as-is, not generated by this console'}
            </span>
          </span>
        </div>
      )}

      {block.kind === 'evidence' && (
        <p className="compiled__note">
          Held on case file{block.receivedAt ? `, received ${formatDate(block.receivedAt)}` : ''}. Transmitted with this response.
        </p>
      )}

      {block.redactions?.length > 0 && (
        <p className="compiled__note">
          Redacted for {[...new Set(block.redactions.map((r) => r.retention))].join(', ').toLowerCase()} by{' '}
          {block.audit?.by} on {formatDateTime(block.audit?.at)}. The unredacted original was not retained.
        </p>
      )}
    </section>
  );
}

export function PacketPreview({ open, onClose, c, packet, assessment, onSubmit, canSubmit }) {
  const brand = useBrand();
  if (!packet) return null;

  const included = packet.blocks.filter((b) => b.included !== false);
  const narrative = included.filter((b) => b.kind === 'narrative');
  const exhibits = included.filter((b) => b.kind !== 'narrative');

  return (
    <Modal
      open={open}
      onClose={onClose}
      title="Compiled representment"
      subtitle={`Case ${c.id} · ${exhibits.length} exhibit${exhibits.length === 1 ? '' : 's'} · this is what gets sent`}
      size="xl"
      footer={
        <>
          <span className="micro subtle" style={{ marginRight: 'auto' }}>
            {assessment.missingRequired.length === 0
              ? 'Every required exhibit is present.'
              : `Missing: ${assessment.missingRequired.map((i) => i.label).join(', ')}`}
          </span>
          <Button variant="secondary" onClick={onClose}>Back to editor</Button>
          <Button variant="primary" icon="send" disabled={!canSubmit} onClick={onSubmit}>Submit packet</Button>
        </>
      }
    >
      <div className="compiled">
        <div className="doc-page__brand">
          <span className="doc-page__logo">
            <img src={brand.logo} alt="" width={16} height={16} style={{ borderRadius: 3 }} />
            {brand.name}
          </span>
          <span className="doc-page__meta">
            REPRESENTMENT<br />
            {brand.legalName}
          </span>
        </div>

        <p className="doc-page__re">
          RE: Case {c.id} · ARN {c.arn ?? '—'} · {c.networkLabel ?? brand.terms.claimProgramme} {c.reasonCode} ·{' '}
          {formatCurrency(c.disputeAmount, c.currency)}
        </p>

        {narrative.map((b) => (
          <div key={b.id} className="compiled__section">
            <h3 className="compiled__section-head">{b.title}</h3>
            {b.body.split('\n').map((line, i) => (
              line.trim() ? <p key={i}>{line}</p> : <br key={i} />
            ))}
          </div>
        ))}

        {exhibits.length > 0 && (
          <div className="compiled__section">
            <h3 className="compiled__section-head">Enclosures</h3>
            <ol className="compiled__index">
              {exhibits.map((b, i) => (
                <li key={b.id}>
                  Exhibit {i + 1} — {b.title}
                  {b.uploaded && <span className="nano subtle"> · supplied by the merchant</span>}
                </li>
              ))}
            </ol>
          </div>
        )}

        {exhibits.map((b, i) => <Exhibit key={b.id} block={b} index={i + 1} />)}

        <div className="doc-page__sig">
          <div>Yours faithfully,</div>
          <div style={{ marginTop: 14, fontWeight: 700 }}>Disputes Team</div>
          <div>{brand.legalName}</div>
          <div className="doc-page__meta" style={{ textAlign: 'left' }}>{brand.supportEmail}</div>
        </div>
      </div>
    </Modal>
  );
}

export default PacketPreview;
